### PR TITLE
Python 3.5 compatibility

### PR DESCRIPTION
**Pull request by hroncok**
While keeping compatibility with 2.7. I left 2.6 unchecked.

### CODE REVIEW

**Comment by rfk** [comment]
Thanks @hroncok!  Looks like you're still adding commits, ping me when you're ready for me to take a look at this.

**Comment by hroncok** [comment]
I've just added that one (I forgot about classifiers). That's it, please take a look.

**Comment by rfk** [comment]
>  I left 2.6 unchecked.

👍

**Comment by hroncok** [comment]
In case you don't care anymore about 2.6, I can also remove it form the classifiers.

**Comment by rfk** [comment]
>  I can also remove it form the classifiers.

That would be great, thanks.  I think it's time I stopped caring about 2.6 in my projects.

**Comment by hroncok** [comment]
Amended.

**Comment by rfk** [comment]
This LGTM, thanks again!  I'll make a new release with these changes included.

**Comment by hroncok** [comment]
Thanks. And thanks for this project, I was searching for it and was very happy that it exists.

**Pull request merged**
